services:

    database:
        image: mariadb
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
        ports:
            - '4455:3306'
        volumes:
            - './volumes/database:/var/lib/mysql'